/**
 * Mock request data for admin dashboard preview mode.
 * Used when Supabase is not yet configured.
 * TO REMOVE: connect NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY.
 */
import type { RequestRow } from "@/types/database";

export const MOCK_REQUESTS: RequestRow[] = [
  {
    id: "mock-001",
    request_number: "NI-260101-4821",
    item_request:
      "I need 25 commercial walk-in refrigerator units for a restaurant chain expansion in the Dallas-Fort Worth area. They must be stainless steel, Energy Star certified, and 48 cubic feet minimum.",
    budget: "$250,000",
    budget_numeric: 250000,
    deadline: "2026-03-15",
    deadline_is_flexible: false,
    delivery_location: "Dallas, TX",
    full_name: "Marcus Johnson",
    email: "marcus.johnson@example.com",
    phone: "214-555-0182",
    company_name: "Lone Star Restaurant Group",
    additional_details:
      "Must be compatible with our existing refrigeration monitoring system (TempGuard Pro). Prefer staggered delivery — 10 units first, then 15 units 30 days later.",
    confirmed_legitimate: true,
    agreed_to_terms: true,
    status: "new",
    priority: "urgent",
    ai_summary:
      "B2B bulk refrigerator procurement for a multi-location restaurant group. High-value, well-specified request with clear quantity and compliance requirements. Strong purchase intent.",
    ai_score: 9.1,
    ai_category: "Commercial Kitchen Equipment",
    ai_clarity_score: 10,
    ai_seriousness_score: 9,
    ai_profitability_score: 9,
    ai_risk_flags: [],
    ai_recommended_questions: [
      "Do you have a preferred brand (True, Traulsen, Hoshizaki)?",
      "Is electrical 208V or 115V?",
      "Do you require installation services?",
    ],
    ai_recommendation: "pursue",
    fallback_score: null,
    admin_notes: null,
    source: "web",
    utm_source: "google",
    utm_medium: "cpc",
    utm_campaign: "restaurant-equipment",
    blocked: false,
    viewed_at: null,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-002",
    request_number: "NI-260101-7743",
    item_request:
      "Looking to source 500 branded polo shirts and 200 baseball caps for a corporate event in June. Need embroidery with our logo on chest.",
    budget: "$8,500",
    budget_numeric: 8500,
    deadline: "2026-05-20",
    deadline_is_flexible: false,
    delivery_location: "Chicago, IL",
    full_name: "Sarah Chen",
    email: "sarah@example.com",
    phone: "312-555-0093",
    company_name: "Apex Solutions Inc.",
    additional_details: "Colors: navy blue and white. Sizes: S through XXL. Need mockup approval before production.",
    confirmed_legitimate: true,
    agreed_to_terms: true,
    status: "reviewing",
    priority: "high",
    ai_summary:
      "Corporate branded apparel order for a mid-size company event. Clear specs, deadline, and budget. Straightforward sourcing opportunity.",
    ai_score: 7.3,
    ai_category: "Promotional Merchandise",
    ai_clarity_score: 8,
    ai_seriousness_score: 7,
    ai_profitability_score: 7,
    ai_risk_flags: [],
    ai_recommended_questions: [
      "Do you need individual packaging?",
      "Preferred material (100% cotton vs. performance blend)?",
    ],
    ai_recommendation: "pursue",
    fallback_score: null,
    admin_notes: "Spoke with Sarah on 1/3. She confirmed the timeline and wants a quote by end of week.",
    source: "web",
    utm_source: null,
    utm_medium: null,
    utm_campaign: null,
    blocked: false,
    viewed_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-003",
    request_number: "NI-260101-2256",
    item_request:
      "Need 3 food trucks fully equipped for a music festival. Each truck should be able to serve 500+ people per day. Propane, full commercial kitchen setup.",
    budget: "Not sure",
    budget_numeric: null,
    deadline: null,
    deadline_is_flexible: true,
    delivery_location: "Austin, TX",
    full_name: "Derek Williams",
    email: "derek@festivalco.com",
    phone: "512-555-0344",
    company_name: "FestivalCo Events",
    additional_details: null,
    confirmed_legitimate: true,
    agreed_to_terms: true,
    status: "needs_information",
    priority: "normal",
    ai_summary:
      "Food truck rental inquiry for a large event. Budget is unclear and no deadline set. Needs follow-up to qualify budget and event date before moving forward.",
    ai_score: 5.2,
    ai_category: "Event Equipment Rental",
    ai_clarity_score: 6,
    ai_seriousness_score: 5,
    ai_profitability_score: 5,
    ai_risk_flags: ["No budget specified", "No deadline specified"],
    ai_recommended_questions: [
      "What is your total budget for the food trucks?",
      "What are the festival dates?",
      "Is this a purchase or rental?",
    ],
    ai_recommendation: "manually_review",
    fallback_score: null,
    admin_notes: null,
    source: "web",
    utm_source: null,
    utm_medium: null,
    utm_campaign: null,
    blocked: false,
    viewed_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-004",
    request_number: "NI-260101-9901",
    item_request:
      "50 industrial-grade standing desks and ergonomic chairs for new office buildout. Height-adjustable desks preferred.",
    budget: "$45,000",
    budget_numeric: 45000,
    deadline: "2026-02-28",
    deadline_is_flexible: false,
    delivery_location: "New York, NY",
    full_name: "Priya Patel",
    email: "priya@techstartup.io",
    phone: "646-555-0771",
    company_name: "TechStartup IO",
    additional_details: "Prefer white or light grey. Need assembly included in quote.",
    confirmed_legitimate: true,
    agreed_to_terms: true,
    status: "potential_match",
    priority: "normal",
    ai_summary:
      "Office furniture bulk order for a growing tech company. Clear specs and timeline. Good candidate for a fast-turn quote.",
    ai_score: 7.8,
    ai_category: "Office Furniture",
    ai_clarity_score: 8,
    ai_seriousness_score: 8,
    ai_profitability_score: 7,
    ai_risk_flags: [],
    ai_recommended_questions: [
      "What is the max desk height range needed?",
      "Do you need cable management accessories?",
    ],
    ai_recommendation: "pursue",
    fallback_score: null,
    admin_notes: "Identified 2 suppliers. Waiting on quotes. Following up Monday.",
    source: "web",
    utm_source: "linkedin",
    utm_medium: "social",
    utm_campaign: null,
    blocked: false,
    viewed_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
